services:
  db:
    image: postgres:16
    container_name: queuedesk_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: queuedesk
    ports:
      - "5432:5432"
    volumes:
      - queuedesk_pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: queuedesk_api
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  queuedesk_pgdata:
